export const MEMBER_KYC_PROFILE_FIELDS = [
  'first_name',
  'middle_name',
  'middle_initial',
  'last_name',
  'name_suffix',
  'date_of_birth',
  'country_of_birth',
  'nationality',
  'email',
  'phone_mobile',
  'phone_office',
  'residential_street',
  'residential_line_2',
  'residential_city',
  'residential_state',
  'residential_postal_code',
  'residential_country',
  'is_us_citizen',
  'is_us_taxpayer',
  'us_taxpayer_id',
  'country_of_tax_residency',
  'tax_id_number',
  'id_type',
  'id_number',
  'id_issue_date',
  'id_expiry_date',
  'id_issuing_country',
  'proof_of_address_date',
  'ownership_percentage',
] as const

