var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/portfolio/route.js")
R.c("server/chunks/6d6b6_@supabase_node-fetch_lib_index_fe5efd57.js")
R.c("server/chunks/6d6b6_next_6bcf5441._.js")
R.c("server/chunks/6d6b6_tr46_f7ca97fb._.js")
R.c("server/chunks/6d6b6_@supabase_auth-js_dist_module_4ebeb219._.js")
R.c("server/chunks/6d6b6_e5e892f7._.js")
R.c("server/chunks/[root-of-the-server]__011803d2._.js")
R.c("server/chunks/versotech-portal__next-internal_server_app_api_portfolio_route_actions_40201e30.js")
R.m("[project]/versotech-portal/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/versotech-portal/src/app/api/portfolio/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/versotech-portal/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/versotech-portal/src/app/api/portfolio/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
