var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(public)/versoholdings/login/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__49c5b33b._.js")
R.c("server/chunks/ssr/versotech-portal_b55dcd2d._.js")
R.c("server/chunks/ssr/versotech-portal_aef81660._.js")
R.c("server/chunks/ssr/[root-of-the-server]__360885fe._.js")
R.c("server/chunks/ssr/6d6b6_next_dist_compiled_@opentelemetry_api_index_43be286c.js")
R.c("server/chunks/ssr/[root-of-the-server]__c515b3c3._.js")
R.c("server/chunks/ssr/6d6b6_next_dist_0861cf16._.js")
R.c("server/chunks/ssr/6d6b6_next_dist_49938f89._.js")
R.c("server/chunks/ssr/versotech-portal_src_app_54a486a2._.js")
R.c("server/chunks/ssr/6d6b6_next_dist_client_components_builtin_global-error_294b5185.js")
R.c("server/chunks/ssr/[root-of-the-server]__a1518c7a._.js")
R.c("server/chunks/ssr/versotech-portal_src_app_not-found_tsx_a900f219._.js")
R.c("server/chunks/ssr/6d6b6_next_dist_client_components_bf7b8690._.js")
R.c("server/chunks/ssr/6d6b6_next_dist_client_components_builtin_unauthorized_b8598cc4.js")
R.c("server/chunks/ssr/c6ad4__next-internal_server_app_(public)_versoholdings_login_page_actions_e986843c.js")
R.m(664373)
module.exports=R.m(664373).exports
