var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/deals/[id]/faqs/route.js")
R.c("server/chunks/6d6b6_@supabase_node-fetch_lib_index_4f6374eb.js")
R.c("server/chunks/6d6b6_next_58745fe4._.js")
R.c("server/chunks/6d6b6_tr46_f7ca97fb._.js")
R.c("server/chunks/6d6b6_@supabase_auth-js_dist_module_4ebeb219._.js")
R.c("server/chunks/6d6b6_zod_v4_e2c118fe._.js")
R.c("server/chunks/6d6b6_e5e892f7._.js")
R.c("server/chunks/[root-of-the-server]__a27daa4a._.js")
R.c("server/chunks/c6ad4__next-internal_server_app_api_deals_[id]_faqs_route_actions_e48b68e8.js")
R.m("[project]/versotech-portal/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/versotech-portal/src/app/api/deals/[id]/faqs/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/versotech-portal/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/versotech-portal/src/app/api/deals/[id]/faqs/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
