var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/partners/me/fee-models/route.js")
R.c("server/chunks/6d6b6_@supabase_node-fetch_lib_index_6b1f3707.js")
R.c("server/chunks/6d6b6_next_e53d2f52._.js")
R.c("server/chunks/6d6b6_tr46_f7ca97fb._.js")
R.c("server/chunks/6d6b6_@supabase_auth-js_dist_module_4ebeb219._.js")
R.c("server/chunks/6d6b6_e5e892f7._.js")
R.c("server/chunks/[root-of-the-server]__49be9410._.js")
R.c("server/chunks/c6ad4__next-internal_server_app_api_partners_me_fee-models_route_actions_a45a1041.js")
R.m("[project]/versotech-portal/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/versotech-portal/src/app/api/partners/me/fee-models/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/versotech-portal/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/versotech-portal/src/app/api/partners/me/fee-models/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
