name: Publish Scheduled Documents

on:
  schedule:
    # Runs every hour to check for documents scheduled to be published
    - cron: '0 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call publish-documents endpoint
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            ${{ secrets.VERCEL_URL }}/api/cron/publish-documents
